const applicationTitle = 'MonoManagement';
const applicationName = 'Mono Management';
const Duration defaultTimeout = Duration(seconds: 20);
const int apiConnectTimeout = 20000;
const int apiSendTimeout = 20000;
const int apiReceiveTimeout = 60000;
const Duration apiTimeout = Duration(seconds: 20);
const String baseApiUrl = 'https://api.monobank.ua/';
const String accessToken = 'ubUgYeqVFDEHoKNpCtq_jSxTMVGAt22DSPIO6jSV9N2w';
